name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env: 
      working-directory: Lisp.Transpiler
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: pwd
      run: pwd
    - name: Install dependencies
      run: dotnet restore
      working-directory: Lisp.Compiler
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: Lisp.Compiler
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: Lisp.Compiler
